service: vue-multiple-pages

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: server.entrance.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  versionFunctions: false
  region: ap-southeast-1
  vpc:
    securityGroupIds:
      - ${opt:security-group}
    subnetIds:
      - ${opt:subnet-a}
      - ${opt:subnet-b}
      - ${opt:subnet-c}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
